---

- name: Create Golden-Images for Oracle Database, Oracle Restart
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  roles:
    - oraswdb-golden-image
    - oraswgi-golden-image
