---

- name: Host configuration
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  roles:
    - common
    - orahost
    - orahost-storage
    - name: orahost-ssh
      when: configure_cluster | default(false)
    - cxoracle
    - orahost-logrotate

  post_tasks:
    - name: Restart autofs
      service: name=autofs enabled=yes state=restarted
      tags: autofs
