---
collections:
  - name: community.general
    version: 7.0.0
  - name: devsec.hardening
    version: 8.6.0
  - name: opitzconsulting.ansible_oracle
    version: 4.3.0

  # Development only settings!
  # - source: ./../ansible-oracle
  #   type: dir
  # - name: https://github.com/Rendanic/ansible-oracle.git
  #   type: git
  #   version: pr/lsof
