---
collections:
  - name: devsec.hardening
    version: 8.2.0
  - name: opitzconsulting.ansible_oracle
    version: 3.2.0
  # - name: https://github.com/Rendanic/ansible-oracle.git
  #   type: git
  #   version: master
