---
- name: Oracle Grid Infrastructure / Restart installation & ASM Configuration
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  roles:
    - oraswgi-install
    - oraswgi-manage-patches
    - oraasm-manage-diskgroups
