# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# PLEASE START 1st with following command to create additional disks!
#
# VAGRANT_EXPERIMENTAL=disks vagrant up

Vagrant.configure("2") do |config|

  lanip = "192.168.56.162"
  vm_name = "has19c-162"
  vm_hostname = "has19c-192-168-56-162.nip.io"

  # Please define the folder to the extracted archives from Oracle
  #
  config.vm.synced_folder ENV['VAGRANT_ANSIBLE_ORACLE_SW'], "/sw/oracle", disabled: false, mount_options: ["ro"]

  config.vm.disk :disk, size: "150GB", name: "#{vm_name}_oracle"
  config.vm.disk :disk, size: "30GB", name: "#{vm_name}_asmdata1"
  config.vm.disk :disk, size: "30GB", name: "#{vm_name}_asmfra1"
  
  # config.disksize.size = '50GB'
  config.vm.box =  "Rendanic/oraclelinux-8.x"

  puts " "
  puts " Oracle Restart"
  puts " "
  puts " Hostname: #{vm_hostname}"
  puts " IP:       #{lanip}"
  puts " Logins:"
  puts "           vagrant / vagrant"
  puts "           root    / vagrant"
  puts " "
  puts " Please do the 1st start with following command to create the additional disks!"
  puts " VAGRANT_EXPERIMENTAL=disks vagrant up"
  puts " "

  config.vm.box_check_update = true

  config.vm.network :private_network, ip: lanip

  # config.vm.network "public_network"
  config.ssh.insert_key = true
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.hostname = vm_hostname

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "8500"
    vb.cpus = 2
    vb.name = vm_name
    vb.customize ["modifyvm", :id, "--groups", "/ansible-oracle"]

  end


  config.vm.provision "shell", inline: <<-SHELL

    if [ ! -b /dev/sdb ]; then
      echo "Please start the Box with following command once to create the addional disks!"
      echo "VAGRANT_EXPERIMENTAL=disks vagrant up"
      exit 1
    fi

    sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd.service

    yum install -y gcc make perl kernel-uek-devel
    yum update -y
    /sbin/rcvboxadd quicksetup all

  SHELL
end
