---
configure_public_yum_repo: false
configure_motd: false

configure_cluster: false
role_separation: false
configure_oracle_sudo: true
disable_EE_options: true
autostartup_service: true

control_management_pack_access: NONE

configure_hugepages_by: memory

# disable hugepages on small systems
# don't forget to enable use_large_pages in oracle parameter
# size_in_gb_hugepages: 2
size_in_gb_hugepages: 0

oracle_stage: /u01/stage

configure_host_disks: true

host_fs_layout:
  - vgname: vgora
    state: present
    filesystem:
      - {mntp: /u01, lvname: lvorabase, lvsize: 40G, fstype: xfs}
    disk:
      - {device: /dev/sdb, pvname: /dev/sdb1}
