version: '3.3'
services:
  ansible:
    build: .
    container_name: ansible-oracle-2.12.6
    image: ansible:2.12.6
    hostname: ansible-oracle
    mem_limit: 1000m
    privileged: true
    working_dir: /git/ansible-oracle-inventory
    volumes:
      # binding for workdir
      - type: bind
        source: ${GIT_SOURCE_FOLDER-./../..}
        target: /git
      - ${SSH_AUTH_SOCK}:/ssh-agent:ro
      - ansible_galaxy:/ansible/galaxy:rw
    environment:
      - "PS1=$$(hostname):$$(pwd) $$ "
      - SSH_AUTH_SOCK=/ssh-agent
      - ANSIBLE_COLLECTIONS_PATHS=/ansible/galaxy
volumes:
  ansible_galaxy:
