# -*- mode: ruby -*-
# vi: set ft=ruby :

# shell provisioner code
$script = <<-SCRIPT
  # openjdk is needed for ocmp-documentation project
  # shellcheck for VSCode
  apt install -y openjdk-8-jdk shellcheck

  # copy public key to vagrant user
  ssh_public_key=/vagrant/id_rsa.pub
  if test -f "$ssh_public_key" ; then
    echo "Check if public key $ssh_public_key is valid."
    if ssh-keygen -l -f "$ssh_public_key" ; then
      echo "Add public key to /home/vagrant/.ssh/authorized_keys"
      cat "$ssh_public_key" >> /home/vagrant/.ssh/authorized_keys
    fi
  fi

  curl -q -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    chmod a+x /usr/local/bin/docker-compose

  test -d /home/vagrant/git || (mkdir /home/vagrant/git ; chown vagrant /home/vagrant/git)
  
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.disksize.size = '100GB'
  config.vm.box_check_update = true
  config.vm.network "private_network", ip: "192.168.56.99"
  config.ssh.insert_key = true
  config.vm.hostname = "ansible-192-168-56-99.nip.io"

  puts " "
  puts " Ansible-Controller for ansible-oracle"
  puts " "
  puts " Hostname: ansible-192-168-56-99.nip.io"
  puts " IP:       192.168.56.99"
  puts " "


  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 2
    vb.name = "ansible-99"

    config.vm.provision "docker"
    config.vm.provision "shell", inline: $script
  end
end
