# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# PLEASE START 1st with following command to create additional disks!
#
# VAGRANT_EXPERIMENTAL=disks vagrant up

Vagrant.configure("2") do |config|

  # Please define the folder to the extracted archives from Oracle
  #
  config.vm.synced_folder ENV['VAGRANT_ANSIBLE_ORACLE_SW'], "/sw/oracle", disabled: false, mount_options: ["ro"]

  config.vm.disk :disk, size: "150GB", name: "has21c-163_oracle"
  config.vm.disk :disk, size: "30GB", name: "has21c-163_asmdata1"
  config.vm.disk :disk, size: "30GB", name: "has21c-163_asmfra1"

  # config.disksize.size = '50GB'
  config.vm.box =  "Rendanic/oraclelinux-8.x"

  config.vm.box_check_update = true

  config.vm.network "private_network", ip: "192.168.56.163"

  # config.vm.network "public_network"
  config.ssh.insert_key = true
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.hostname = "has21c-192-168-56-163.nip.io"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "8500"
    vb.cpus = 2
    vb.name = "has21c-163"
    vb.customize ["modifyvm", :id, "--groups", "/ansible-oracle"]

  end


  config.vm.provision "shell", inline: <<-SHELL

    if [ ! -b /dev/sdb ]; then
      echo "Please start the Box with following command once to create the addional disks!"
      echo "VAGRANT_EXPERIMENTAL=disks vagrant up"
      exit 1
    fi

    sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd.service

    lvresize -L 2g /dev/rootvg/swaplv
    swapoff -a
    mkswap /dev/rootvg/swaplv
    swapon -a

    cd /usr/local; git clone --recursive  https://github.com/Rendanic/SQL-Zauberkasten.git

    yum install -y gcc make perl kernel-uek-devel
    yum update -y
    /sbin/rcvboxadd quicksetup all

  SHELL
end
