---
apply_patches_db: true
db_homes_config:
  db1920_si_ee: &db1920_si_ee
    version: 19.3.0.0
    oracle_home: /u01/app/oracle/product/19/db1920-si-ee
    edition: EE
    opatch_minversion: 12.2.0.1.36
    state: present
    opatchauto: []
    opatch:
      - patchid: 35320081
        # Database Release Update 19.20.0.0.230718
        patchversion: 19.20.0.0.230718
        stop_processes: true
        state: present
      - patchid: 35354406
        # Oracle JavaVM Component Release Update (OJVM RU) 19.20.0.0.230718
        stop_processes: true
        state: present
      - patchid: 35512813
        # DATAPUMP BUNDLE PATCH 19.20.0.0.0
        stop_processes: true
        state: present

  db1919_si_ee: &db1919_si_ee
    version: 19.3.0.0
    oracle_home: /u01/app/oracle/product/19/db1919-si-ee
    edition: EE
    opatch_minversion: 12.2.0.1.36
    state: present
    opatchauto: []
    opatch:
      - patchid: 35042068
        # Database Release Update 19.19.0.0.230418
        patchversion: 19.19.0.0.230418
        stop_processes: true
        state: present
      - patchid: 35050341
        # Oracle JavaVM Component Release Update (OJVM RU) 19.19.0.0.230418
        stop_processes: true
        state: present
      - patchid: 35261302
        # DATAPUMP BUNDLE PATCH 19.19.0.0.0
        stop_processes: true
        state: present

  # Current Mapping of ORACLE_HOMEs
  # use this mapping for fast change between the Release Updates
  # <<: * => merge values from alias and overwrite oracle_home + home
  db19-si-ee:
    <<: *db1920_si_ee
    # imagename: db_home_19.13.zip
    oracle_home: /u01/app/oracle/product/19/db1
    oracle_home_name: db19_si_ee
    readonly_home: true

db_homes_installed:
  - home: db19-si-ee
    apply_patches: true
    state: present

oracle_sw_patches:
  - filename: p35320081_190000_Linux-x86-64.zip
    patchid: 35320081
    version: 19.3.0.0
    description: Database Release Update 19.20.0.0.230718
    creates: 35320081/README.txt
  - filename: p35354406_190000_Linux-x86-64.zip
    patchid: 35354406
    version: 19.3.0.0
    description: OJVM RELEASE UPDATE 19.20.0.0.0
    creates: 35354406/README.txt
  - filename: p35512813_1920000DBRU_Generic.zip
    patchid: 35512813
    version: 19.3.0.0
    description: DATAPUMP BUNDLE PATCH 19.20.0.0.0
    creates: 35512813/README.txt
