---

- name: Install Oracle Autonomous Health Framework (AHF)
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  roles:
    - opitzconsulting.ansible_oracle.oraswahf_install
