---
- name: Configure devsec Security on Hosts
  hosts: all
  any_errors_fatal: true
  become: true
  become_user: root
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
