---

- name: Create Golden-Images for Oracle Database, Oracle Restart
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  collections:
    - opitzconsulting.ansible_oracle
  roles:
    - oraswdb_golden_image
    - oraswgi_golden_image
