---

- name: Database Server Patching
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  collections:
    - opitzconsulting.ansible_oracle
  roles:
    - oraswdb_manage_patches
    - oradb_datapatch
