# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# PLEASE START 1st with following command to create additional disks!
#
# VAGRANT_EXPERIMENTAL=disks vagrant up

Vagrant.configure("2") do |config|

  # Please define the folder to the extracted archives from Oracle
  # 
  config.vm.synced_folder ENV['VAGRANT_ANSIBLE_ORACLE_SW'], "/sw/oracle", disabled: false, mount_options: ["ro"]

  config.vm.disk :disk, size: "100GB", name: "dbrestart162_oracle"
  config.vm.disk :disk, size: "50GB", name: "dbrestart162_oracle_ASM_DATA1"
  config.vm.disk :disk, size: "50GB", name: "dbrestart162_oracle_ASM_FRA1"

  # config.disksize.size = '50GB'
  config.vm.box =  "Rendanic/oraclelinux-7.x"

  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.56.162"

  # config.vm.network "public_network"
  config.ssh.insert_key = true
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  
  config.vm.hostname = "dbrestart162.local"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.cpus = 2
    vb.name = "dbrestart162"
    vb.customize ["modifyvm", :id, "--groups", "/ansible-oracle"]

  end


  config.vm.provision "shell", inline: <<-SHELL

    if [ ! -b /dev/sdb ]; then
      echo "Please start the Box with following command once to create the addional disks!"
      echo "VAGRANT_EXPERIMENTAL=disks vagrant up"
      exit 1
    fi

    sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd.service

    yum install -y oracle-epel-release-el7
    yum install -y git mc tree tig glances bash-completion

    # resize /tmp
    lvresize -L 1800m /dev/mapper/rootvg-tmplv
    resize2fs /dev/mapper/rootvg-tmplv

    lvresize -L 2g /dev/rootvg/swaplv
    swapoff -a
    mkswap /dev/rootvg/swaplv
    swapon -a

    cd /usr/local; git clone --recursive  https://github.com/Rendanic/SQL-Zauberkasten.git

    test -d /home/vagrant/git || mkdir /home/vagrant/git
    cd /home/vagrant/git
    test -d /home/vagrant/git/ansible-oracle || git clone -b oc --recursive https://github.com/opitzconsulting/ansible-oracle.git
    test -d /home/vagrant/git/ansible-oracle-inventory || git clone --recursive https://github.com/opitzconsulting/ansible-oracle.git

    chown -R vagrant:vagrant /home/vagrant/git

    # create ssh-keys for passwordless login in ansible-oracle on localhost
    test -f /home/vagrant/.ssh/id_rsa || (cat /dev/zero | ssh-keygen -q -P '' -f /home/vagrant/.ssh/id_rsa)
    cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    chown -R vagrant:vagrant /home/vagrant/

    yum install -y gcc make perl kernel-uek-devel
    yum update -y
    /sbin/rcvboxadd quicksetup all

  SHELL
end
